language: go
install:
  - export HUGO_VERSION=0.20
  - export HUGO_PACKAGE=hugo_${HUGO_VERSION}_Linux-64bit
  - curl -L https://github.com/spf13/hugo/releases/download/v$HUGO_VERSION/$HUGO_PACKAGE.tar.gz | tar xz
  - mkdir $HOME/bin
  - mv ./hugo_${HUGO_VERSION}_linux_amd64/hugo_${HUGO_VERSION}_linux_amd64 $HOME/bin/hugo
script:
  - rm -rf docs
  - cd DOCUMENTATION/_settings
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email: false
